package domain;

public enum RockStarDBStatus {
    DB_USER_ALREADY_EXISTS,
    DB_USER_ADDED,
    DB_USER_FAILED_TO_SAVE,

    DB_USER_LOGIN_SUCCESS,
    DB_USER_LOGIN_FAILED,

    DB_INCORRET_FORMAT_NUMBER,

    DB_MUSIC_ADDED,
    DB_MUSIC_NAME_EMPTY, DB_MUSIC_NAME_FAILED, DB_MUSIC_NAME_HAS_CHANGED,
    DB_MUSIC_PRICE_HAS_CHANGED,DB_MUSIC_VISIBILITY_CHANGED,DB_MUSIC_VISIBILITY_FAIL,
    DB_MUSIC_ALREADY_EXISTS_IN_THE_PLAYLIST,
    DB_ALBUM_NAME_FAILED, DB_ALBUM_NAME_HAS_CHANGED, DB_CART_EMPTY,

    DB_SONG_ALREADY_IN_CART,
    DB_SONG_ADDED_TO_CART,
    DB_SONG_ALREADY_BOUGHT,
    DB_SONGS_PURCHASED_SUCCESSFULLY,
    DB_INSUFFICIENT_BALANCE,

    DB_SOME_FIELD_IS_EMPTY,
    DB_PLAYLIST_NAME_ALREADY_EXISTS,
    DB_PLAYLIST_GENERATED_SUCCESSFULLY,
    DB_MUSIC_CANT_BE_ADDED_TO_PLAYLISTS,
    DB_NO_SONGS_ADDED_TO_PLAYLIST,
    DB_PLAYLIST_GENERATED_BUT_WITHOUT_WANTED_SIZE, DB_PLAYLIST_VISIB_CHANGED, DB_PLAYLIST_VISIB_UNCHANGED,

}
